apiVersion: apps/v1
kind: Deployment
metadata:
  name: mock-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mock-app
  template:
    metadata:
      labels:
        app: mock-app
    spec:
      containers:
        - name: mock-app
          image: mock-app:latest
          ports:
            - containerPort: 8000